# GitPod (https://www.gitpod.io/) workspace configuration
# See https://www.gitpod.io/docs/configure/workspaces
image: maven:3-eclipse-temurin-8

tasks:
  - name: Fetch Dependencies and Build
    before: |
      mkdir /home/gitpod/.m2
      printf '<settings>\n  <localRepository>/workspace/m2-repository/</localRepository>\n</settings>\n' > /home/gitpod/.m2/settings.xml; clear
    init: mvn install -Pquick -Daether.dependencyCollector.impl=bf -T.5C
  - name: Add upstream GitHub repo
    init: git remote add github https://github.com/gchq/Gaffer.git || true
    # Ensure only a GitHub noreply email is used for commits
    command: |
      if ! [[ $(git config --global --get user.email) =~ .*@users.noreply.github.com ]]; then git config --global --remove-section user;
      if ! [[ $(git config --local --get user.email) =~ .*@users.noreply.github.com ]]; then git config --local --remove-section user; clear;
      echo "Git global/local user details weren't set or weren't using a GitHub noreply email. Specify them with 'git config --local'.";
      else clear; fi; else clear; fi;

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - vscjava.vscode-maven

